CREATE TABLE MA_USER (
    USER_ID bigint NOT NULL,
    LOGIN_ID VARCHAR(100) NOT NULL,
    LOGIN_PW VARCHAR(100) NOT NULL,
    CREATE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT '0001-01-01 00:00:00',
    PRIMARY KEY (USER_ID),
    UNIQUE (LOGIN_ID)
);
CREATE SEQUENCE user_id_seq INCREMENT 1 START 1 MINVALUE 1;
CREATE INDEX idx_login_id ON MA_USER (LOGIN_ID);