CREATE TABLE TR_PW_MANAGE (
    PW_ID NUMERIC(10) NOT NULL,
    PW_NAME VARCHAR(30) NOT NULL,
    PW_VALUE VARCHAR(100) NOT NULL,
    MEMO VARCHAR(100),
    CREATE_TIMESTAMP VARCHAR(20) NOT NULL,
    LAST_UPDATED_TIMESTAMP VARCHAR(20) NOT NULL,
    PRIMARY KEY (PW_ID),
    UNIQUE (PW_NAME)
);

CREATE INDEX idx_pw_name ON TR_PW_MANAGE (PW_NAME);