CREATE TABLE MA_USER (
    USER_ID NUMERIC(10) NOT NULL,
    GROUP_ID NUMERIC(10) NOT NULL,
    LOGIN_ID VARCHAR(30) NOT NULL,
    LOGIN_PW VARCHAR(100) NOT NULL,
    CREATE_TIMESTAMP VARCHAR(20) NOT NULL,
    LAST_UPDATED_TIMESTAMP VARCHAR(20) NOT NULL,
    PRIMARY KEY (USER_ID),
    UNIQUE (LOGIN_ID)
);

CREATE INDEX idx_login_id ON MA_USER (LOGIN_ID);