CREATE TABLE TR_AUTH_MANAGE (
    USER_ID bigint NOT NULL,
    ACCESS_TOKEN VARCHAR(64) NOT NULL,
    EXPIRED_DATE TIMESTAMP NOT NULL,  --有効期限を切って毎度チェックする。切れたら強制ログアウト
    CREATE_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_TIMESTAMP TIMESTAMP NOT NULL DEFAULT '0001-01-01 00:00:00',
    PRIMARY KEY (USER_ID)
);
